apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnia-dz-2026
  labels:
    app: omnia-dz-2026
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omnia-dz-2026
  template:
    metadata:
      labels:
        app: omnia-dz-2026
    spec:
      containers:
        - name: omnia-dz-2026
          image: omnia-dz-2026
          ports:
            - containerPort: 80
