apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnia-dz-2022
  labels:
    app: omnia-dz-2022
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omnia-dz-2022
  template:
    metadata:
      labels:
        app: omnia-dz-2022
    spec:
      containers:
      - name: omnia-dz-2022
        image: omnia-dz-2022
        ports:
        - containerPort: 80
