apiVersion: apps/v1
kind: Deployment
metadata:
  name: predcasno-glasovanje-referendum-jek2
  labels:
    app: predcasno-glasovanje-referendum-jek2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predcasno-glasovanje-referendum-jek2
  template:
    metadata:
      labels:
        app: predcasno-glasovanje-referendum-jek2
    spec:
      containers:
        - name: predcasno-glasovanje-referendum-jek2
          image: predcasno-glasovanje-referendum-jek2
          ports:
            - containerPort: 80
