apiVersion: apps/v1
kind: Deployment
metadata:
  name: predcasno-glasovanje-predsednik-2022
  labels:
    app: predcasno-glasovanje-predsednik-2022
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predcasno-glasovanje-predsednik-2022
  template:
    metadata:
      labels:
        app: predcasno-glasovanje-predsednik-2022
    spec:
      containers:
        - name: predcasno-glasovanje-predsednik-2022
          image: predcasno-glasovanje-predsednik-2022
          ports:
            - containerPort: 80
