apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: predcasno-glasovanje-dz-2022
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: predcasno-glasovanje-dz-2022
    newName: rg.fr-par.scw.cloud/djnd/predcasno-glasovanje-dz-2022
    newTag: '625b2bcb6e6bab29d2e5f98067902399266d00e0'
