apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: omnia-dz-2026
    newName: rg.fr-par.scw.cloud/djnd/omnia-dz-2026
    newTag: '9a8351aa3a71f246123e2e9f72db6d4101c6ef23'
