apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: omnia-za
    newName: rg.fr-par.scw.cloud/djnd/omnia-za
    newTag: 'af24769ca9f0763a290f9be723f900c466c7728f'
