apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: predcasno-glasovanje-dz-2026
    newName: rg.fr-par.scw.cloud/djnd/predcasno-glasovanje-dz-2026
    newTag: 'da16e9fa20fec5f4b9d2b7549a097cd0d402c55c'
