apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: predcasno-glasovanje-referendum-jek2
    newName: rg.fr-par.scw.cloud/djnd/predcasno-glasovanje-referendum-jek2
    newTag: '2a0c323133d0672e45edfb0faa10ee1e806620a7'
