apiVersion: v1
kind: Service
metadata:
  name: predcasno-glasovanje-referendum-dostojna-smrt-2025
spec:
  selector:
    app: predcasno-glasovanje-referendum-dostojna-smrt-2025
  ports:
    - protocol: TCP
      port: 80
